SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS UGB, USED_GOODS_REPLY AS UGR
WHERE UGB.BOARD_ID = UGR.BOARD_ID AND UGB.CREATED_DATE BETWEEN '20221001' AND '20221031'
ORDER BY UGR.CREATED_DATE, TITLE;